### ISSUE TITLE
Token pooling vs mean pooling

### ISSUE THREAD

**Issue by schmika** [vidarlab/xformer-paired-viz#1]
Hi and thank you for sharing your research on GitHub!

We would like to apply your approach to the Vision Transformer model `vit_tiny_patch16_224` that is included in the [Pytorch Image Models (timm)](https://timm.fast.ai/) library.
We have modified the network so that it outputs attention weights and prepooled embeddings. However, `vit_tiny_patch16_224` seems to use the CLS token for global pooling. As I understood your code, you are using mean pooling for the final network output, which determines how you compute the spatial similarity map:
https://github.com/vidarlab/xformer-paired-viz/blob/6ef0c80423ca2a6883c0319ccdec4c56508c8d0d/src/visualization_functions.py#L17-L18
Is it possible to adapt your approach to visualize paired image similarity for networks that use token pooling instead of mean pooling?

**Comment by sblack15** [comment]
Hi, thank you for your interest in our work. 

Unfortunately, our method only works when using mean pooling, not token pooling. If you don't absolutely need to use token pooling, though, then in Timm you can easily change the architecture to use mean pooling instead.  

`model = timm.create_model('vit_tiny_patch16_224', global_pool='avg')`

**Comment by schmika** [comment]
Thank you for your quick response and your advice! We will see whether we can use mean pooling.
